version: '2'
services:
  php:
    image: php_img
    volumes:
      - ./:/app
    working_dir: /app
  web:
    image: nginx_img
    volumes:
      - ./:/app
    depends_on:
      - php
    ports:
      - 80:80
  mysql:
    image: mysql:8.0.22
    volumes:
      - ./:/app
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=students
      - MYSQL_ROOT_PASSWORD=root
    working_dir: /app
volumes:
  dbdata:
