# Generated by Django 3.1.2 on 2020-11-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Name', models.CharField(max_length=50)),
                ('USN', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Branch', models.CharField(max_length=3)),
            ],
        ),
    ]
